### ISSUE TITLE
Wrong `invalid.illegal.character-not-allowed-here.html` font style

### ISSUE THREAD

**Issue by nandordudas** [subframe7536/vscode-theme-maple#1]
I'm using the `Maple Theme` and there is a non-expected token if I'm using self closing tags in HTML.

> [!NOTE]
>
> - `Windows 11 23H2` with `WSL 2`
> - VSCode: `1.93.1`
> - `Maple-Mono 6.4` (and `^7` too)
> - Extension: `v0.4.5`
> - ligature settings change has no effect

Code:

```vue
<template>
  <UContainer data-layout="default">
    <slot />
  </UContainer>
</template>
```

https://github.com/user-attachments/assets/282baf03-e431-4617-9c2d-2144e9f01fc3

**Comment by nandordudas** [comment]
I made fix with workspace settings:

```jsonc
{
  "editor.tokenColorCustomizations": {
    "[Maple Light][Maple Dark]": {
      "textMateRules": [
        {
          "scope": "invalid.illegal.character-not-allowed-here.html",
          "settings": {
            "fontStyle": ""
          }
        }
      ]
    }
  }
}
```

![image](https://github.com/user-attachments/assets/f4667145-1add-4544-bbac-d10d389ac6b8)

**Comment by subframe7536** [comment]
Thanks for detailed issue, I will fix it later

**Comment by nandordudas** [comment]
No issue found. Thanks! 🤗 
The `Vs Code` extension has been updated to `v0.4.6`.
